TI Project requirements
bSI-InfraRoom/TI-Bridge pull request #1
Opened 2023-05-10 19:43 UTC by SergejMuhic

1. created Project root with requriements

2023-05-15 14:00 UTC, pjanck requested changes
I've only read through the xml code and did not load this in any UI.

2023-05-15 14:00 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
I believe that this syntax is 1.0. We might consider updating the syntax to be in line with version 1.1 or 1.2.

2023-05-15 14:00 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
Let's add (similarly to length units) a conversion based unit for pounds.

2023-05-15 14:00 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +				</DocTemplateUsage>
At imperial check (I assume that would be line 125):
- Fahrenheit is missing from checking parameters
- ConversionUnitType RuleID should be used, and not SIUnitType

2023-05-15 14:00 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Project_Global_Positioning_3J9e0D0k14GeJdkFjFtWG0" />
I am confused about `Site` mention, however the `href` points to `Project_Global_Positioning..`: the latter uses `IfcGeometricRepresentationContext` and not `IfcSite`. Is this a mistake or just a similar naming without intent to imply any connection?

2023-05-18 18:07 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Project_Global_Positioning_3J9e0D0k14GeJdkFjFtWG0" />
Not sure I understand the question. It is a judgement from the description of the requirement. Names are just identifiers, the requirement describes the test. We can argue about what to do about it but from my point of view "Site within project describing geospatial location and project boundaries." requires geospatial location first and foremost. Project boundaries I honestly do not understand.

2023-05-21 19:24 UTC, pjanck reviewed
Reviewed the last two commits only. I still need to go through the whole content as indicated in the PR's description.

2023-06-06 08:35 UTC, pjanck requested changes
Using mvdXML Grammar to define rules, not the encoding in the reviewed file:

2023-06-06 08:35 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +						<DocTemplateItem UniqueId="986637a8-b557-46e2-826d-f2ba63ee6ac7" RuleParameters="HasUnits=IfcUnitAssignment;SIUnitType=MASSUNIT;SIUnitName=GRAM;" />
In order to conform to "SI Kilograms are the default", one would need to include a check for `SIPrefix[VALUE]='KILO'`.

2023-06-06 08:38 UTC, pjanck requested changes
Goes with previous review (forgot to submit ...).

2023-06-06 08:38 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +						<DocTemplateItem UniqueId="dd3cdeb3-b37d-4910-87a7-6cf081e954ac" RuleParameters="HasUnits=IfcUnitAssignment;SIUnitType=LENGTHUNIT;SIUnitName=METRE;" />
Similarly to kilograms, one would need to check that `SIPrefix[EXISTS]=FALSE` for the case of "SI Meters are the default". Compare:

    #1 = IFCSIUNIT(*, .LENGTHUNIT., $, .METRE.);
    #2 = IFCSIUNIT(*, .LENGTHUNIT., .MILLI., .METRE.);

Both lines would pass the current rule.

2023-10-15 19:21 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +						<DocTemplateItem UniqueId="986637a8-b557-46e2-826d-f2ba63ee6ac7" RuleParameters="HasUnits=IfcUnitAssignment;SIUnitType=MASSUNIT;SIUnitName=GRAM;" />
This should be fine now.

2023-10-15 19:21 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +						<DocTemplateItem UniqueId="dd3cdeb3-b37d-4910-87a7-6cf081e954ac" RuleParameters="HasUnits=IfcUnitAssignment;SIUnitType=LENGTHUNIT;SIUnitName=METRE;" />
Have a proposal committed on how to deal with it in the spec. I'd have to implement serialization. Let me know what you think.

2023-10-17 15:37 UTC, pjanck approved these changes
LFTM

Very neat solution, adding the `SIPrefix` RuleID!

2023-10-17 15:45 UTC, pjanck approved these changes

2023-10-17 15:46 UTC, larswik approved these changes

2023-10-22 16:28 UTC, merged