TI Site requirements
bSI-InfraRoom/TI-Bridge pull request #2
Opened 2023-05-10 19:50 UTC by SergejMuhic

1. initial commit with Name and Bridge requirements

2023-05-11 06:31 UTC, larswik approved these changes
I think that this is a good start that we can work with.

2023-05-15 14:05 UTC, pjanck approved these changes
Updating to 1.1 syntax for parameter strings. I am unsure how this is handled internally, though.

2023-05-15 14:05 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +						<DocTemplateItem UniqueId="e76f143a-90eb-4b24-bde9-ae14d9e78e18" RuleParameters="ObjectName=HDMI Plattrambro;" />
```suggestion
						<DocTemplateItem UniqueId="e76f143a-90eb-4b24-bde9-ae14d9e78e18" RuleParameters="ObjectName[Value]='HDMI Plattrambro'" />
```

2023-05-15 14:05 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +						<DocTemplateItem UniqueId="57319180-2ea6-4688-b8e4-f04b377802b0" RuleParameters="RelatedObjects=IfcBridge;" />
```suggestion
						<DocTemplateItem UniqueId="57319180-2ea6-4688-b8e4-f04b377802b0" RuleParameters="RelatedObjects[Type]='IfcBridge'" />
```

2023-05-16 20:49 UTC, pjanck commented
> Updating to 1.1 syntax for parameter strings.

Disregard this.

2023-05-25 14:00 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +				</DocTemplateUsage>
Top `DocTemplateUsage` has an attribute `Operator="or"`, the bottom doesn't. Intentional?

2023-05-25 14:05 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +				</DocTemplateUsage>
Nope, corrected.

2023-05-31 14:27 UTC, pjanck requested changes
I am missing `Spatial containment` on:

- boring point
- geomodel
- geotechnical stratum

Are these not required?

2023-06-21 10:28 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Boreholes shall be placed localy with _IfcLocalPlacement_.</Documentation>
```suggestion
					<Documentation>Boreholes shall be placed locally with _IfcLocalPlacement_.</Documentation>
```

2023-06-21 10:28 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be represented as a 3D surface tesselation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```suggestion
					<Documentation>Surface Proposed shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric item.</Documentation>
```

2023-06-21 10:28 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +		</DocConceptRoot>
Should we already account for https://github.com/bSI-InfraRoom/IFC-Specification/pull/651 and use _IfcGeoScienceModel_?

2023-06-21 10:28 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Boreholes shall be placed localy with _IfcLocalPlacement_.</Documentation>
```suggestion
					<Documentation>Boreholes shall be placed locally with _IfcLocalPlacement_.</Documentation>
```

2023-06-21 14:32 UTC, pjanck requested changes
Consistency improvements + mismatch between *Proposed* and *Existing* - I suggest a review of all documentation in this PR.

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Boreholes shall be placed localy with _IfcLocalPlacement_.</Documentation>
```suggestion
					<Documentation>Boreholes shall be placed locally with _IfcLocalPlacement_.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +				</DocTemplateUsage>
Capitalization of site/Site is inconsistent in documentation nodes.

```suggestion
				<DocTemplateUsage Name="Bridge" UniqueId="7554fcb5-f806-44b6-aabf-b741ca557728">
					<Documentation>Bridge structure(s) within site.</Documentation>
					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Spatial_Decomposition_1cVuH3xCvAZQOan_h15FW" />
					<Items>
						<DocTemplateItem UniqueId="57319180-2ea6-4688-b8e4-f04b377802b0" RuleParameters="RelatedObjects=IfcBridge;SpatialElementName=2-2241-1;" />
					</Items>
				</DocTemplateUsage>
				<DocTemplateUsage Name="Project" UniqueId="a9a7d68d-c84f-4fae-b753-f975c296bef8">
					<Documentation>The site shall be contained in a project.</Documentation>
					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Spatial_Composition_2C3zBtSRjEReR30ApKl5A" />
					<Items>
						<DocTemplateItem UniqueId="6effeb6a-ec4c-4587-8d33-df811fca5cfd" RuleParameters="RelatingObject=IfcProject;ProjectName=8448590;" />
					</Items>
				</DocTemplateUsage>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be locally placed in the Site.</Documentation>
```suggestion
				<DocTemplateUsage Name="Product Local Placement" UniqueId="437748ef-61eb-485d-92d2-7cdc615a1805">
					<Documentation>Surface Proposed shall be locally placed in the site.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be represented as a 3D surface tesselation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```suggestion
				<DocTemplateUsage Name="Geometry" UniqueId="35622964-9cc2-47ae-aeb1-e465fcb77330">
					<Documentation>Surface Proposed shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be locally placed in the Site.</Documentation>
```suggestion
					<Documentation>Surface Proposed shall be locally placed in the site.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be represented as a 3D surface tesselation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```suggestion
					<Documentation>Surface Proposed shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be represented as a 3D surface tesselation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```suggestion
					<Documentation>Surface Proposed shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be locally placed in the Site.</Documentation>
```suggestion
					<Documentation>Surface Proposed shall be locally placed in the site.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be represented as a 3D surface tesselation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```suggestion
					<Documentation>Surface Proposed shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be locally placed in the Site.</Documentation>
```suggestion
					<Documentation>Surface Proposed shall be locally placed in the site.</Documentation>
```

2023-06-21 14:32 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +			<Documentation>Ground surface of the Site indicating final conditions modelled as _IfcGeotechnicalStratum_.</Documentation>
Mismatch between `DocConceptRoot.Name` and `DocConceptRoot.Documentation` - Surface *Proposed* vs. *final* conditions?

2023-10-22 17:16 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +				</DocTemplateUsage>
I think I should do it the other way around. So everything capitalized.

2023-10-22 17:22 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +			<Documentation>Ground surface of the Site indicating final conditions modelled as _IfcGeotechnicalStratum_.</Documentation>
That is how it is defined in the requirements analysis.

2023-10-24 12:16 UTC, pjanck requested changes
Two new typos, one old one, otherwise good to go!

2023-10-24 12:16 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
Coming from the RAR:

```suggestion
		<DocConceptRoot Name="Surface Existing Geotechnical Stratum" UniqueId="ff6a0881-d581-4823-bf99-5de40cf90fc7">
			<ApplicableEntity xsi:type="DocEntity" xsi:nil="true" href="IfcGeotechnicalStratum" />
			<Concepts>
				<DocTemplateUsage Name="Product Local Placement" UniqueId="fcd93046-3f50-4811-8df0-7a0575188e8d">
					<Documentation>Surface Existing shall be locally placed in the Site.</Documentation>
					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Product_Local_Placement_3Bw5jVUH9AGukt7cEGB9j" />
					<Items>
						<DocTemplateItem UniqueId="52a2105e-9d63-46e3-a4c6-b88b707a2364" RuleParameters="RelativeToElement=IfcSite;ElementName=HDMI Plattrambro;" />
					</Items>
				</DocTemplateUsage>
				<DocTemplateUsage Name="Geometry" UniqueId="fec732b0-336c-4139-aeaf-9c0e419136b5">
					<Documentation>Surface Existing shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```

2023-10-24 12:16 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Surface Proposed shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
From RAR:

```suggestion
		<DocConceptRoot Name="Surface Existing Geomodel" UniqueId="7db57e42-f8fb-454c-aa0d-5f803c837b8c">
			<ApplicableEntity xsi:type="DocEntity" xsi:nil="true" href="IfcGeomodel" />
			<Concepts>
				<DocTemplateUsage Name="Product Local Placement" UniqueId="437748ef-61eb-485d-92d2-7cdc615a1805">
					<Documentation>Surface Existing shall be locally placed in the Site.</Documentation>
					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Product_Local_Placement_3Bw5jVUH9AGukt7cEGB9j" />
					<Items>
						<DocTemplateItem UniqueId="db040752-8fee-45c7-ba17-78eeaa936a13" RuleParameters="RelativeToElement=IfcSite;ElementName=HDMI Plattrambro;" />
					</Items>
				</DocTemplateUsage>
				<DocTemplateUsage Name="Geometry" UniqueId="35622964-9cc2-47ae-aeb1-e465fcb77330">
					<Documentation>Surface Existing shall be represented as a 3D surface tessellation _IfcTriangulatedIrregularNetwork_ geometric items.</Documentation>
```

2023-10-28 08:03 UTC, merged