Ti/alignment
bSI-InfraRoom/TI-Bridge pull request #8
Opened 2023-05-18 18:54 UTC by SergejMuhic

1. created the first draft for alignment TI based on requirements analysis of IFC Bridge

2023-05-21 19:31 UTC, pjanck requested changes

2023-05-21 19:31 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +						<DocTemplateItem UniqueId="3aa5783a-10bd-465c-b2ef-abbe2e73317a" RuleParameters="ObjectName=All datasets name alignment &apos;Alignmemt&apos;;" />
```suggestion
						<DocTemplateItem UniqueId="3aa5783a-10bd-465c-b2ef-abbe2e73317a" RuleParameters="ObjectName=All datasets name alignment &apos;Alignment&apos;;" />
```

2023-05-21 19:31 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Alignment shall define an axis curve, which may consist of a horizontal alignment curve only, a horizontal curve and vertical curve.</Documentation>
```suggestion
					<Documentation>Alignment shall define an axis curve, which may consist of a horizontal alignment curve only, or both a horizontal and a vertical curve.</Documentation>
```

2023-05-21 19:31 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
I assume that the `IfcPolyline` could be 3D. Propose to use Axis 3D Geometry instead.

2023-05-21 19:31 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
Propose to add rule: `IfcAlignment.ObjectPlacement.PlacementRelTo = NIL`. I am unsure about the syntax within IfcDoc.

2023-05-25 13:48 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +						<DocTemplateItem UniqueId="3aa5783a-10bd-465c-b2ef-abbe2e73317a" RuleParameters="ObjectName=All datasets name alignment &apos;Alignmemt&apos;;" />
I will change this template a bit.

2023-05-25 13:49 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					<Documentation>Alignment shall define an axis curve, which may consist of a horizontal alignment curve only, a horizontal curve and vertical curve.</Documentation>
Not changing this yet. Requirements are from bridge RA.

2023-05-25 13:51 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
I think I should add it to both. It is not clear in the requirements.

2023-05-25 13:53 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
Looks like I have to add that feature. Cannot find that option. Maybe it serialized correctly in mvdxml already. Have to check that first.

2023-05-25 13:55 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
Nope, feature to add.

2023-06-05 14:21 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
As a `TemplateRule.Parameter` in mvdXML Grammar, using [Product Local Placement](https://bsi-infraroom.github.io/IFC-Documentation-Tunnel/4_4_0_0/general/HTML/link/product-local-placement.htm) concept template:

> RelativeToElement[EXISTS]=FALSE

2023-10-17 15:47 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge/DocModelView.xml
> +					</Items>
Given the proposal from #1, this would look like:

> RelativeToElement:NOTEXISTS

2023-10-24 12:39 UTC, pjanck approved these changes
There are merge conflicts that should be addressed before merging. Otherwise LFTM.

2023-11-03 07:47 UTC, merged