Started with TI-Superstructure
bSI-InfraRoom/TI-Bridge pull request #9
Opened 2023-05-26 09:10 UTC by larswik

2023-05-31 14:23 UTC, pjanck requested changes
I would greet filled in `documentation` XML nodes as the case in other PRs.

2023-05-31 14:23 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
Are '?' in lines 113, 121 and 129 intentional? Were you trying to steer a discussion?

2023-05-31 14:23 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
The inner most `DocTemplateUsage` is referencing `Object_Predefined_Type`, however no rule parameters were defined. Intentional?

2023-05-31 14:23 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +								</DocTemplateUsage>
I am not convinced about the `TypePredefinedType` rule id: is the intention to only apply to the connected `IfcTypeObject` (i.e. `IfcElementAssemblyType.PredefinedType`)?

2023-05-31 14:23 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
Looking forward to how this will turn out.

2023-05-31 14:23 UTC, pjanck commented on IFC4x3/Templates/Object Connectivity/Spatial Structure/Spatial Container/Spatial Container PredefinedType/DocTemplateDefinition.xml
> +								</DocModelRuleEntity>
The `Reference` would need an `IdPrefix='Type'` to use `TypePredefinedType` as a rule id, I believe.

2023-06-05 13:34 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +		<DocConceptRoot Name="Girder Segment" UniqueId="5d25181b-c624-45c3-b4b2-16f9f5e8fede">
I see that we should probably bring this one either together with the showcase from AASHTO or remove the other one completely.

2023-06-05 13:34 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Object_User_Identity_31di66dFr7AJKdxDG2D1A" />
Would be great if you added the descriptions from the RA report. I will wait for those to not have to switch back and forth between the RA report and the PR.

2023-06-05 13:34 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Path_Connectivity_1G5mELXyP9BgRydr_42n5F" />
Have to start thinking about adding the values, otherwise these are more usages for the AbRV or Bridge RV or whatever MVD it would turn out to be.

2023-06-05 13:34 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				<DocTemplateUsage Name="Alignments" UniqueId="4dc839ff-3200-49fd-b765-8426124d3a3f">
I would propose to re-use this. I have put some thought into it already. See https://github.com/bSI-InfraRoom/TI-Bridge/blob/ae9381221f18493e005fb18cfcf5f02f27ea02fe/IFC4x3/ModelViews/TI-Bridge/DocModelView.xml#L60

2023-06-05 13:34 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				<DocTemplateUsage Name="Alignment" UniqueId="5e82185b-39f1-457c-9dcd-09c34a4772d2">
Maybe we need to revise the template. I will add the ruleIDs update to your repo so that you can access nested template ruleIDs.

2023-06-05 13:38 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
> Are '?' in lines 113, 121 and 129 intentional? Were you trying to steer a discussion?

They will be gone after I get the IfcDoc update from @SergejMuhic.

2023-06-05 13:39 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
> The inner most `DocTemplateUsage` is referencing `Object_Predefined_Type`, however no rule parameters were defined. Intentional?

Waiting for IfcDoc update...

2023-06-20 07:17 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Object_User_Identity_31di66dFr7AJKdxDG2D1A" />
Done.

2023-06-20 07:18 UTC, larswik commented
Remaining issues for now (in addition to open comments above):
- Superstructure-alignments?
- Element Decomposition Predefined Type - Can't select IfcBeam/PredefinedType - list has predefined types for root (e.g. IfcElementAssembly)
- Concrete parameters (names, materials, stations, ...)
- Girder Segment
	- Connection head/tail/support
		- Element Connectivity With Realizing ELement (new CT)
		- Element Connectivity With Realizing Element with Predefined Type?
		- Connection support connecting to "substructure"...?
	- Element Connectivity With Realizing Element (new CT for Girder Segment - Connection Support)
	- Reinforcing embedded - IfcReinforcingBar (Decomposition?)
	- Tendons embedded - IfcTendon (Decomposition?)
	- Stiffeners - IfcPlate/STIFFENER_PLATE? (Decomposition?)
	- Camber (the camber of a beam may be defined by ASSIGNING a StructuralCurveMember with displacement coordinates?)
- How do we specify more than one instance? Do we need tables on the side specifying parameters?
- Cross frame
	- How to specify girder segment left/right? (ConnectedFrom/ConnectedTo)
	- How to specialize for IfcReferent and Station?
- Diaphragm
	- Connection head/tail (How to be able to specify ConnectedTo => IfcBeam/GIRDER_SEGMENT?)
	- Connection support connecting to "substructure"...?
	- Reinforcing (Decomposition?)
	- Tendons (Decomposition?)
- Truss
	- Element decomposition predefined type (see above)
	- Connection to "substructure"?

2023-06-20 11:20 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
```suggestion
				<DocTemplateUsage Name="Material" UniqueId="a23c9639-1794-468c-875f-3621a7b4576c">
					<Documentation>Material of the diaphragm.</Documentation>
					<Definition xsi:type="DocTemplateDefinition" Name="Material" UniqueId="05b10ba1-5fb2-4d43-ac50-875fc9c85e58" />
				</DocTemplateUsage>
```

2023-06-26 07:29 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Path_Connectivity_1G5mELXyP9BgRydr_42n5F" />
I needed a structure before thinking of adding values.

2023-06-26 08:25 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +								</DocTemplateUsage>
Strange indeed. Didn't show up in the IfcDoc UI? Should be fixed now  with https://github.com/bSI-InfraRoom/TI-Bridge/pull/9/commits/11bd24d5859e92952dd7d8ff99bec3e6b6b7a95f

2023-06-26 08:27 UTC, larswik commented on IFC4x3/Templates/Object Connectivity/Spatial Structure/Spatial Container/Spatial Container PredefinedType/DocTemplateDefinition.xml
> +								</DocModelRuleEntity>
This needs a bit of elaboration so I understand what to do exactly.

2023-09-25 11:07 UTC, larswik commented
Remaining issues in attached document. 
[TI Bridge - Superstructure.pdf](https://github.com/bSI-InfraRoom/TI-Bridge/files/12714329/TI.Bridge.-.Superstructure.pdf)

2023-10-12 09:43 UTC, larswik commented
Update 2023-10-12 - remaining main issues:
- Superstructure => Alignments
- Girder => Axis offset curve
- Girder segment => Camber
- Diaphragm => Connection support (connecting diaphragm to superstructure)
- Truss => Connections (connecting truss to other superstructure elements)

2023-10-13 11:05 UTC, pjanck requested changes

2023-10-13 11:05 UTC, pjanck commented on IFC4x3/Templates/Object Connectivity/Element Connectivity/Element Connectivity with Predefined Type/DocTemplateDefinition.xml
> +						<DocModelRuleAttribute Name="RelatedElement" Identification="RelatedElement">
Both rules have the same `Identification`, which will lead to confusion when writing rules. Propose to remove the one on `DocModelRuleEntity`.

2023-10-18 08:29 UTC, pjanck requested changes
I haven't looked through the whole `DocModelView`, but let's first resolve these comments before I continue.

2023-10-18 08:29 UTC, pjanck commented on IFC4x3/Templates/Object Connectivity/Element Connectivity/Element Connectivity with Predefined Type/DocTemplateDefinition.xml
> +										<DocTemplateDefinition xsi:nil="true" href="Object_Predefined_Type_0b989XcDzD2fDaLbDNNAGX" />
Propose to add a prefix to the `Reference` node, e.g. `RelatedElement`. This enables easier uniqueness of RuleIDs while checking.

2023-10-18 08:29 UTC, pjanck commented on IFC4x3/Templates/Structural Curve Assignment/DocTemplateDefinition.xml
This whole ConceptTemplate, while fairly in-depth, only defines one `Identification`, thus only one setting can be checked for. Is this intentional?

2023-10-18 08:29 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
There is an item without any `RuleParameters` in line 438. Intentional?

2023-10-18 08:29 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
There are items without any `RuleParameters` in lines 427 and 428. Intentional?

2023-10-18 08:29 UTC, pjanck commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
This seems incomplete. Please double check. (It might be ok - I'm curious how the mvdXML will look like here.)

2023-10-24 13:45 UTC, larswik commented on IFC4x3/Templates/Object Connectivity/Spatial Structure/Spatial Container/Spatial Container PredefinedType/DocTemplateDefinition.xml
> +								</DocModelRuleEntity>
Ping @SergejMuhic and @pjanck: Can we have a look at this together?

2023-10-24 13:46 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +		<DocConceptRoot Name="Girder Segment" UniqueId="5d25181b-c624-45c3-b4b2-16f9f5e8fede">
> I see that we should probably bring this one either together with the showcase from AASHTO or remove the other one completely.

How do we decide that?

2023-10-24 13:54 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Path_Connectivity_1G5mELXyP9BgRydr_42n5F" />
A bit unclear to me how to specify e.g. Name when there are more than one instance, e.g. "Girder Segment". Is seems to be possible to specify e.g. regular_expression. Possible in IfcDoc?

2023-10-24 14:31 UTC, larswik commented on IFC4x3/Templates/Structural Curve Assignment/DocTemplateDefinition.xml
> This whole ConceptTemplate, while fairly in-depth, only defines one `Identification`, thus only one setting can be checked for. Is this intentional?

We'll have to check this. I tried to emulate a CT that @SergejMuhic sent me as an image. I might have missed important information.

2023-10-24 14:33 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
> There is an item without any `RuleParameters` in line 438. Intentional?

It seems like IfcDoc sometimes adds these "empty items". Maybe I need to go through and manually remove these?

2023-10-24 14:34 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
> There are items without any `RuleParameters` in lines 427 and 428. Intentional?

See response to previous comment.

2023-10-27 08:30 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +					<Definition xsi:type="DocTemplateDefinition" xsi:nil="true" href="Path_Connectivity_1G5mELXyP9BgRydr_42n5F" />
I will add names for elements and materials (wherever I can put in a value).

2023-10-27 09:09 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				<DocTemplateUsage Name="Alignment" UniqueId="5e82185b-39f1-457c-9dcd-09c34a4772d2">
We would need a station template from BuildingSMART.

2023-10-27 09:10 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				<DocTemplateUsage Name="Alignment" UniqueId="5e82185b-39f1-457c-9dcd-09c34a4772d2">
> Maybe we need to revise the template. I will add the ruleIDs update to your repo so that you can access nested template ruleIDs.

We need a station CT from BuildingSMART for this.

2023-10-27 09:11 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				</DocTemplateUsage>
> This seems incomplete. Please double check. (It might be ok - I'm curious how the mvdXML will look like here.)

We need a station CT from BuildingSMART for this.

2023-10-27 11:06 UTC, larswik commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				<DocTemplateUsage Name="Alignments" UniqueId="4dc839ff-3200-49fd-b765-8426124d3a3f">
Partly resolved using CT "Axis Offset Curve". Some hacking still required.

2023-10-27 11:07 UTC, larswik commented on IFC4x3/Templates/Structural Curve Assignment/DocTemplateDefinition.xml
We have no more requirements for this so can't do more at this stage.

2023-10-28 08:59 UTC, SergejMuhic commented on IFC4x3/ModelViews/TI-Bridge-Superstructure/DocModelView.xml
> +				<DocTemplateUsage Name="Alignment" UniqueId="5e82185b-39f1-457c-9dcd-09c34a4772d2">
Since the template needs to go back to the alignment as it is an alignment reference, I think we need a new basis. I have compiled a proposal in the alignment instruction if you look at the Bridge root. I will merge and reassign. No need to do anything in this PR then.

2023-11-03 07:53 UTC, SergejMuhic approved these changes

2023-11-03 07:54 UTC, merged